### ISSUE TITLE
Can correlation-id passed with http request?

### ISSUE THREAD

**Issue by adibPlaybuzz** [toboid/correlation-id#1]
As micro-services are orchestrated working with each other - it will be effective to use this mechanism between different services, what do you think?

**Comment by toboid** [comment]
Hi. Unfortunately not. This module provides a way to have a consistent id across any calls within a single process, not across the network. 

If I provide a way in this module of setting the id for a context, you could then send the id along in your http request and set it in the downstream service. It's a bit manual but would allow you to trace calls across services.

I can definitely see the value of this for my own work too. I'd be interested in writing something to support it (probably another module that uses this) but not sure when i'll get round to it. I'll reply here when/if I do write something. Please do keep me posted about how you get on.

**Comment by adibiton** [comment]
Hi,
I'm willing to support, let's agree on some spec.
I thought about providing express middleware which enhances response header based on corrlation-id/request header.

What do you think?

**Comment by toboid** [comment]
Sounds great and doesn't seem like too much work either. 

Yes i agree that a header is the best way to go, something like `x-correlation-id`?

We could create middleware that checks for the header on the incoming request, if it's there then set the correlation id to that value (would need to add that ability to this module) otherwise create a new one.

For outgoing requests to downstream services the header could be added to individual requests manually. It might be possible to automatically add it to all downstream requests but I'm not sure off the top of my head how that would work, or whether it's really a good idea? Any thoughts?

I don't think this functionality really belongs in this repo so have created a new one [here](https://github.com/toboid/express-correlation-id) that could use this module.

**Comment by toboid** [comment]
Express mw is available here: https://github.com/toboid/express-correlation-id

**Comment by toboid** [comment]
Going to close this issue, feel free to create another issue here or over at https://github.com/toboid/express-correlation-id if you want to discuss further.
